export const searchQueryResults = {
  threeTracks: {
    tracks: {
      href:
        "https://api.spotify.com/v1/search?query=tobi&type=track&market=AU&offset=0&limit=3",
      items: [
        {
          album: {
            album_type: "single",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/4T8NIfZmVY6TJFqVzN6X49"
                },
                href:
                  "https://api.spotify.com/v1/artists/4T8NIfZmVY6TJFqVzN6X49",
                id: "4T8NIfZmVY6TJFqVzN6X49",
                name: "tobi lou",
                type: "artist",
                uri: "spotify:artist:4T8NIfZmVY6TJFqVzN6X49"
              }
            ],
            available_markets: [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/1JjGKMycjULPogQw8YnDpS"
            },
            href: "https://api.spotify.com/v1/albums/1JjGKMycjULPogQw8YnDpS",
            id: "1JjGKMycjULPogQw8YnDpS",
            images: [
              {
                height: 640,
                url:
                  "https://i.scdn.co/image/354aa96c91e25bb43cc39e27e0aee457ea513558",
                width: 640
              },
              {
                height: 300,
                url:
                  "https://i.scdn.co/image/b16c066fb296b81da80aa8de9295c9798bd4c0c3",
                width: 300
              },
              {
                height: 64,
                url:
                  "https://i.scdn.co/image/2e689c6b2f0ad1d3d2b548d512de5f2e1435383a",
                width: 64
              }
            ],
            name: "tobi lou and the Loop - EP",
            release_date: "2018-04-27",
            release_date_precision: "day",
            total_tracks: 5,
            type: "album",
            uri: "spotify:album:1JjGKMycjULPogQw8YnDpS"
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/4T8NIfZmVY6TJFqVzN6X49"
              },
              href: "https://api.spotify.com/v1/artists/4T8NIfZmVY6TJFqVzN6X49",
              id: "4T8NIfZmVY6TJFqVzN6X49",
              name: "tobi lou",
              type: "artist",
              uri: "spotify:artist:4T8NIfZmVY6TJFqVzN6X49"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          disc_number: 1,
          duration_ms: 215384,
          explicit: true,
          external_ids: {
            isrc: "USUYG1194990"
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/1F1QmI8TMHir9SUFrooq5F"
          },
          href: "https://api.spotify.com/v1/tracks/1F1QmI8TMHir9SUFrooq5F",
          id: "1F1QmI8TMHir9SUFrooq5F",
          is_local: false,
          name: "Buff Baby",
          popularity: 75,
          preview_url:
            "https://p.scdn.co/mp3-preview/df80e5a8c9e38a8ec712a0d81bf89cf3e9120bfd?cid=774b29d4f13844c495f206cafdad9c86",
          track_number: 2,
          type: "track",
          uri: "spotify:track:1F1QmI8TMHir9SUFrooq5F"
        },
        {
          album: {
            album_type: "single",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/4T8NIfZmVY6TJFqVzN6X49"
                },
                href:
                  "https://api.spotify.com/v1/artists/4T8NIfZmVY6TJFqVzN6X49",
                id: "4T8NIfZmVY6TJFqVzN6X49",
                name: "tobi lou",
                type: "artist",
                uri: "spotify:artist:4T8NIfZmVY6TJFqVzN6X49"
              }
            ],
            available_markets: [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/5SKG3BTc7XMqv0BySt3ymf"
            },
            href: "https://api.spotify.com/v1/albums/5SKG3BTc7XMqv0BySt3ymf",
            id: "5SKG3BTc7XMqv0BySt3ymf",
            images: [
              {
                height: 640,
                url:
                  "https://i.scdn.co/image/f5990a4c6059df42ae7b39b8524cd6ecce334995",
                width: 640
              },
              {
                height: 300,
                url:
                  "https://i.scdn.co/image/76e6a77841fada60b6833ae5d206ed869c192a0f",
                width: 300
              },
              {
                height: 64,
                url:
                  "https://i.scdn.co/image/15f91ed2ebaa328e6c956bac881246b13d82b694",
                width: 64
              }
            ],
            name: "Darlin'",
            release_date: "2018-04-23",
            release_date_precision: "day",
            total_tracks: 1,
            type: "album",
            uri: "spotify:album:5SKG3BTc7XMqv0BySt3ymf"
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/4T8NIfZmVY6TJFqVzN6X49"
              },
              href: "https://api.spotify.com/v1/artists/4T8NIfZmVY6TJFqVzN6X49",
              id: "4T8NIfZmVY6TJFqVzN6X49",
              name: "tobi lou",
              type: "artist",
              uri: "spotify:artist:4T8NIfZmVY6TJFqVzN6X49"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          disc_number: 1,
          duration_ms: 205090,
          explicit: true,
          external_ids: {
            isrc: "USUYG1194718"
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/0eGrwX4kf5sV1faR5tZDp3"
          },
          href: "https://api.spotify.com/v1/tracks/0eGrwX4kf5sV1faR5tZDp3",
          id: "0eGrwX4kf5sV1faR5tZDp3",
          is_local: false,
          name: "Darlin'",
          popularity: 60,
          preview_url:
            "https://p.scdn.co/mp3-preview/c5dcf9b0f352009cd350b07e85e79f1eecd549e0?cid=774b29d4f13844c495f206cafdad9c86",
          track_number: 1,
          type: "track",
          uri: "spotify:track:0eGrwX4kf5sV1faR5tZDp3"
        },
        {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify:
                    "https://open.spotify.com/artist/4T8NIfZmVY6TJFqVzN6X49"
                },
                href:
                  "https://api.spotify.com/v1/artists/4T8NIfZmVY6TJFqVzN6X49",
                id: "4T8NIfZmVY6TJFqVzN6X49",
                name: "tobi lou",
                type: "artist",
                uri: "spotify:artist:4T8NIfZmVY6TJFqVzN6X49"
              }
            ],
            available_markets: [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/2MUqGUOIIowuODZV6SMp5P"
            },
            href: "https://api.spotify.com/v1/albums/2MUqGUOIIowuODZV6SMp5P",
            id: "2MUqGUOIIowuODZV6SMp5P",
            images: [
              {
                height: 640,
                url:
                  "https://i.scdn.co/image/dd21b2a824515eb61f5431f0365939bf0b35e6de",
                width: 640
              },
              {
                height: 300,
                url:
                  "https://i.scdn.co/image/b0492fc8f5b83191665cb4401256d4496bd00216",
                width: 300
              },
              {
                height: 64,
                url:
                  "https://i.scdn.co/image/4e8ced634df958ccd27104c72fdb5a7dafc93dbf",
                width: 64
              }
            ],
            name: "tobi lou and the Juice",
            release_date: "2018-08-10",
            release_date_precision: "day",
            total_tracks: 7,
            type: "album",
            uri: "spotify:album:2MUqGUOIIowuODZV6SMp5P"
          },
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/4T8NIfZmVY6TJFqVzN6X49"
              },
              href: "https://api.spotify.com/v1/artists/4T8NIfZmVY6TJFqVzN6X49",
              id: "4T8NIfZmVY6TJFqVzN6X49",
              name: "tobi lou",
              type: "artist",
              uri: "spotify:artist:4T8NIfZmVY6TJFqVzN6X49"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          disc_number: 1,
          duration_ms: 312000,
          explicit: true,
          external_ids: {
            isrc: "USUYG1210950"
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/65lskbT8WoXr7GT3YVjRqW"
          },
          href: "https://api.spotify.com/v1/tracks/65lskbT8WoXr7GT3YVjRqW",
          id: "65lskbT8WoXr7GT3YVjRqW",
          is_local: false,
          name: "Just Keep Goin'",
          popularity: 58,
          preview_url:
            "https://p.scdn.co/mp3-preview/8da0df67e17f7bf1042ae62b46646e31f623d043?cid=774b29d4f13844c495f206cafdad9c86",
          track_number: 7,
          type: "track",
          uri: "spotify:track:65lskbT8WoXr7GT3YVjRqW"
        }
      ],
      limit: 3,
      next:
        "https://api.spotify.com/v1/search?query=tobi&type=track&market=AU&offset=3&limit=3",
      offset: 0,
      previous: null,
      total: 3062
    }
  }
};
